gluster:
  volumes:
    - name: distribute
      type: distributed
      bricks:
        - server-1:
            name: striper1
            size: 10g #ignored for now
        - server-2:
            name: striper2
            size: 5g #ignored for now
    - name: replicer
      type: replica
      count: 2
      bricks:
        - server-2:
            name: replicer2
            size: 2g #ignored for now
        - server-3:
            name: replicer3
            size: 2g  #ignored for now
