---
# init tasks main

- name: Import config.yaml
  include_vars:
    file: config.yaml
    name: config

- name: Update /etc/hosts
  become: yes
  lineinfile:
    path: "/etc/hosts"
    regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
    line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
    state: present
    backup: yes
  when: ansible_hostname != item or ansible_hostname == item
  with_items: "{{groups['servers']}}"

- name: Gather zpool
  stat:
    path: /gpool
  register: zpool_exists

- name: Gather brick pile
  stat:
    path: /gpool/pile
  register: pile_exists

- name: Gather current volumes
  command: gluster volume list
  become: yes
  register: current_volumes
  when: pile_exists.stat.exists == true

- name: Gather current peers
  shell: gluster pool list | grep -v 'UUID' | awk '{print $2}'
  become: yes
  register: current_peers
  when: pile_exists.stat.exists == true

- name: Gather current bricks
  shell: ls /gpool/pile || true
  register: current_bricks

- name: Install glusterfs-server
  apt:
    name: glusterfs-server
    state: present
    update_cache: yes
  become: yes

- name: Make sure glusterd is running
  systemd:
    state: started
    name: glusterd
  become: yes

- name: Install zfs
  apt:
    name: zfs-dkms
    state: present
    update_cache: yes
  become: yes

- name: Create zpools with zfs
  command: zpool create -O compression=lz4 gpool {{ '' if raid == 'striped' else raid }} {{ ' '.join(drives) }}
  when: zpool_exists.stat.exists == false
  become: yes

- name: Create new brick pile (where all the bricks are stored)
  command: zfs create gpool/pile
  become: yes
  when: pile_exists.stat.exists == false

- name: Create new bricks in zfs
  command: zfs create gpool/pile/{{ item.1[inventory_hostname].name }}
  become: yes
  when: inventory_hostname in item.1 and item.1[inventory_hostname].name not in current_bricks.stdout_lines
  with_subelements:
    - "{{ config.gluster.volumes }}"
    - bricks
- name: Peer glusterfs servers
  command: gluster peer probe {{ item }}
  become: yes
  when: inventory_hostname != item
  loop: "{{ ansible_play_hosts }}"
