---
# init tasks main

- name: "Install glusterfs-server"
  apt:
    name: glusterfs-server
    state: present
    update_cache: yes
  become: yes

- name: "Make sure glusterd is running"
  systemd:
    state: started
    name: glusterd
  become: yes

- name: "Install zfs"
  apt:
    name: zfs-dkms
    state: present
    update_cache: yes
  become: yes

- name: "Create zpools with zfs (starting off with striped)"
  command: "zpool create -O compression=lz4 gpool {{ ' '.join(drives.split(',')) }} "
  ignore_errors: yes
  become: yes

- name: "Create dataset to hold bricks"
  command: "zfs create gpool/bricks" 
  ignore_errors: yes
  become: yes

- name: "Create/Start gluster volume"
  gluster.gluster.gluster_volume:
    state: started
    name: gdata1
    bricks: /gpool/bricks/brick1
    rebalance: yes
    cluster:
      "{{ server_ips.split(',') }}"
  run_once: false
  become: yes
