---
# init tasks main

- name: "Install glusterfs-server"
  apt:
    name: glusterfs-server
    state: present
    update_cache: yes
  become: yes

- name: "Make sure glusterd is running"
  systemd:
    state: started
    name: glusterd
  become: yes

- name: "Install zfs"
  apt:
    name: zfs-dkms
    state: present
    update_cache: yes
  become: yes

- name: "Create zpools with zfs"
  command: "zpool create -O compression=lz4 gpool {{ raid == 'striped' ? '' : raid }} {{ ' '.join(drives) }} "
  ignore_errors: yes
  become: yes

- name: "Create dataset to hold all bricks"
  command: "zfs create gpool/bricks"
  ignore_errors: yes
  become: yes

- name: "Gather current volumes"
  command: "gluster volume list"
  become: yes
  register: volumes

- name: "Gather current peers"
  command: "gluster pool list | grep -v 'UUID' | awk '{print $2}'"
  become: yes
  register: peers

- name: "Gather current bricks"
  command: "ls /gpool/bricks"
  register: bricks
